### ISSUE TITLE
.to_unit with subset of measurements

### ISSUE THREAD

**Issue by emersonthis** [mhuggins/ruby-measurement#19]
```
gem 'ruby-measurement'
```

^ with this in my Gemfile, `"dozen".to_unit` works as expected.

When I follow the instructions on the README to load a subset of measurements, `.to_unit` is undefined. Ex:

```
require 'ruby-measurement/measurement'
require 'ruby-measurement/definitions/metric/volume'
require 'ruby-measurement/definitions/metric/weight'
require 'ruby-measurement/definitions/us_customary/volume'
require 'ruby-measurement/definitions/us_customary/weight'
```

Is this expected?

**Comment by mhuggins** [comment]
Yes, this is expected.  It is a way of bypassing changes to global objects.  You can ensure that still works by including that following:

```ruby
require 'ruby-measurement/core_ext'
```

Sorry it's not clear in the documentation, I'd happily accept a PR to address it!

**Comment by emersonthis** [comment]
I think I see what happened, I spaced out and copy/pasted the example from the README without noticing the `require`s instead of `gem`. Closing this and opening a new issue to ask about the right way to do this.

**Comment by emersonthis** [comment]
@mhuggins I just saw your last reply... I'm working on a Rails project. Is there a way to only require the sub-libraries using Bundler?

**Comment by mhuggins** [comment]
Bundler only allows you a single require in lieu of the gem name.  So with that in mind, no. 😄

**Comment by emersonthis** [comment]
Got it. I don’t know much about Bundler (the mark of a good package manager) but it looks like the `require:` option might do this. But I dunno...

**Comment by mhuggins** [comment]
Yeah, the require option will only allow one require though, not multiple.
